import Link from "next/link";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase";
import { getSupabaseAdminClient } from "@/lib/supabaseAdmin";

type DriverApp = { id:string; created_at:string; full_name:string; email:string; phone:string; city:string; state:string; vehicle_type:string; years_experience:string; status:string; license_front_path:string|null; license_back_path:string|null; insurance_path:string|null; registration_path:string|null; };
async function updateStatus(formData: FormData) { "use server"; const id=String(formData.get("id")||""); const status=String(formData.get("status")||""); if(!id||!status) return; await getSupabaseAdminClient().from("driver_applications").update({ status, reviewed_at: new Date().toISOString() }).eq("id", id); redirect("/admin/driver-applications?updated=1"); }
async function getSignedUrl(path: string | null): Promise<string | null> { if (!path) return null; const { data } = await getSupabaseAdminClient().storage.from("driver-documents").createSignedUrl(path, 3600); return data?.signedUrl ?? null; }
export default async function Page({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login?redirect=/admin/driver-applications"); const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).maybeSingle(); if (profile?.role !== "admin") redirect("/");
  const params = await searchParams; const filterStatus = params.status || "all"; let query = getSupabaseAdminClient().from("driver_applications").select("*").order("created_at", { ascending: false }); if (filterStatus !== "all") query = query.eq("status", filterStatus);
  const { data } = await query; const apps = (data ?? []) as DriverApp[]; const enriched = await Promise.all(apps.map(async (app) => ({ ...app, license_front_url: await getSignedUrl(app.license_front_path), license_back_url: await getSignedUrl(app.license_back_path), insurance_url: await getSignedUrl(app.insurance_path), registration_url: await getSignedUrl(app.registration_path) })));
  return <div className="min-h-screen text-white"><main className="section-shell"><div className="max-w-6xl mx-auto"><Link href="/admin/drivers" className="text-xs text-muted hover:text-accent">← Driver Management</Link><h1 className="text-3xl font-bold text-accent mt-2 mb-6">Driver Applications</h1><div className="flex gap-2 mb-6 flex-wrap">{["all","pending","approved","rejected"].map((s)=><Link key={s} href={`/admin/driver-applications${s!=="all"?`?status=${s}`:""}`} className={`px-4 py-2 rounded-lg text-sm ${filterStatus===s?"bg-accent text-black":"surface-glass border border-white/10 text-muted"}`}>{s[0].toUpperCase()+s.slice(1)}</Link>)}</div><div className="space-y-4">{enriched.map((app)=><div key={app.id} className="surface-card p-5 rounded-xl border border-white/10"><div className="flex justify-between"><div><h3 className="text-lg font-semibold">{app.full_name}</h3><p className="text-sm text-muted">{app.email} • {app.phone}</p><p className="text-sm text-muted">{app.city}, {app.state} • {app.vehicle_type} • {app.years_experience}</p></div><span className="text-xs px-2 py-1 rounded bg-white/10">{app.status}</span></div><div className="flex flex-wrap gap-3 mt-3">{app.license_front_url && <a className="text-xs text-accent hover:underline" target="_blank" rel="noreferrer" href={app.license_front_url}>📄 License (Front)</a>}{app.license_back_url && <a className="text-xs text-accent hover:underline" target="_blank" rel="noreferrer" href={app.license_back_url}>📄 License (Back)</a>}{app.insurance_url && <a className="text-xs text-accent hover:underline" target="_blank" rel="noreferrer" href={app.insurance_url}>📄 Insurance</a>}{app.registration_url && <a className="text-xs text-accent hover:underline" target="_blank" rel="noreferrer" href={app.registration_url}>📄 Registration</a>}</div><div className="flex gap-2 mt-4">{["pending","approved","rejected"].map((s)=><form key={s} action={updateStatus}><input type="hidden" name="id" value={app.id} /><input type="hidden" name="status" value={s} /><button className="text-xs px-3 py-1 rounded bg-white/10" disabled={app.status===s}>{s}</button></form>)}</div></div>)}</div></div></main></div>;
}
