import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { getSupabaseAdminClient } from "@/lib/supabaseAdmin";
import { createSupabaseServerClient } from "@/lib/supabase";
import Link from "next/link";

export const metadata: Metadata = { title: "Jax Feature Applications | Admin — Good Hemp Distro" };
type JaxApplication = { id:string; created_at:string; name:string; business_name:string; email:string; phone:string|null; vendor_type:string; why_featured:string; website_url:string|null; instagram_handle:string|null; tiktok_handle:string|null; status:string; user_id:string|null; };

async function updateApplicationStatus(formData: FormData) { "use server"; const id=formData.get("id") as string; const status=formData.get("status") as string; if(!id||!status) return; const admin=getSupabaseAdminClient(); await admin.from("jax_feature_applications").update({ status }).eq("id", id); redirect("/admin/jax-applications?updated=1"); }

export default async function AdminJaxApplicationsPage({ searchParams }: { searchParams: Promise<{ status?: string; updated?: string }>; }) {
  const supabase = await createSupabaseServerClient(); const { data:{ user } } = await supabase.auth.getUser(); if(!user) redirect("/login?redirect=/admin/jax-applications");
  const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).maybeSingle(); if (profile?.role !== "admin") redirect("/");
  const params = await searchParams; const filterStatus = params.status || "all"; const justUpdated = params.updated === "1";
  const admin = getSupabaseAdminClient(); let query = admin.from("jax_feature_applications").select("*").order("created_at", { ascending: false }); if (filterStatus !== "all") query = query.eq("status", filterStatus);
  const { data: applications, error } = await query; const apps = (applications ?? []) as JaxApplication[];
  const total=apps.length,pending=apps.filter((a)=>a.status==="pending").length,approved=apps.filter((a)=>a.status==="approved").length,declined=apps.filter((a)=>a.status==="declined").length;
  const VENDOR_TYPE_LABELS: Record<string, string> = { grower:"Hemp Grower / Farmer", processor:"Processor / Manufacturer", retailer:"Retailer / Dispensary", brand:"Brand / Product Company", service_provider:"Service Provider", educator:"Industry Educator / Consultant", other:"Other" };
  const STATUS_COLORS: Record<string, string> = { pending:"bg-yellow-500/20 text-yellow-300", reviewing:"bg-blue-500/20 text-blue-300", approved:"bg-green-500/20 text-green-300", declined:"bg-red-500/20 text-red-300" };

  return (<div className="min-h-screen text-white"><main className="section-shell"><div className="max-w-6xl mx-auto">
    <div className="flex items-center justify-between mb-8"><div><Link href="/admin" className="text-xs text-muted hover:text-accent mb-2 inline-block">← Admin Dashboard</Link><h1 className="text-3xl font-bold text-accent">Learning with Jax — Feature Applications</h1><p className="text-muted mt-1">Review and manage applicants who want to appear on the show.</p></div></div>
    {justUpdated && <div className="mb-6 p-3 rounded bg-green-500/20 text-green-200 text-sm">✅ Application status updated.</div>}
    {error && <div className="mb-6 p-3 rounded bg-red-500/20 text-red-200 text-sm">Error loading applications: {error.message}</div>}
    <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">{[{label:"Total",value:total,color:"text-white"},{label:"Pending",value:pending,color:"text-yellow-400"},{label:"Approved",value:approved,color:"text-green-400"},{label:"Declined",value:declined,color:"text-red-400"}].map((stat)=><div key={stat.label} className="surface-glass rounded-xl p-5 text-center border border-white/10"><p className={`text-3xl font-bold ${stat.color}`}>{stat.value}</p><p className="text-xs text-muted mt-1 uppercase tracking-wide">{stat.label}</p></div>)}</div>
    <div className="flex gap-2 mb-6 flex-wrap">{["all","pending","reviewing","approved","declined"].map((s)=><Link key={s} href={`/admin/jax-applications${s!=="all"?`?status=${s}`:""}`} className={`px-4 py-2 rounded-lg text-sm font-medium transition ${filterStatus===s?"bg-accent text-black":"surface-glass border border-white/10 text-muted hover:text-white"}`}>{s.charAt(0).toUpperCase()+s.slice(1)}</Link>)}</div>
    {apps.length===0 ? <div className="surface-glass rounded-xl p-10 text-center border border-white/10"><p className="text-muted">No applications found for this filter.</p></div> : <div className="space-y-4">{apps.map((app)=><div key={app.id} className="surface-card p-6 rounded-xl border border-white/10"><div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4 mb-4"><div><div className="flex items-center gap-3 mb-1"><h3 className="font-semibold text-white text-lg">{app.name}</h3><span className={`text-xs px-2 py-1 rounded-full font-medium ${STATUS_COLORS[app.status] ?? "bg-gray-500/20 text-gray-300"}`}>{app.status}</span></div><p className="text-muted text-sm">{app.business_name}</p><p className="text-xs text-muted mt-1">{VENDOR_TYPE_LABELS[app.vendor_type] ?? app.vendor_type}</p></div><div className="text-xs text-muted text-right shrink-0"><p>{new Date(app.created_at).toLocaleDateString("en-US",{year:"numeric",month:"short",day:"numeric"})}</p></div></div><div className="flex flex-wrap gap-4 text-sm text-muted mb-4"><span>📧 <a href={`mailto:${app.email}`} className="hover:text-accent">{app.email}</a></span>{app.phone && <span>📞 {app.phone}</span>}{app.website_url && <span>🌐 <a href={app.website_url} target="_blank" rel="noopener noreferrer" className="hover:text-accent">{app.website_url}</a></span>}{app.instagram_handle && <span>📸 {app.instagram_handle}</span>}{app.tiktok_handle && <span>🎵 {app.tiktok_handle}</span>}</div><div className="surface-glass rounded-lg p-4 mb-4 border border-white/8"><p className="text-xs text-muted uppercase tracking-wide mb-2">Why they want to be featured</p><p className="text-sm text-white/90 leading-relaxed">{app.why_featured}</p></div><div className="flex flex-wrap gap-2 pt-2 border-t border-white/10"><p className="text-xs text-muted self-center mr-2">Update status:</p>{["pending","reviewing","approved","declined"].map((s)=><form key={s} action={updateApplicationStatus}><input type="hidden" name="id" value={app.id} /><input type="hidden" name="status" value={s} /><button type="submit" disabled={app.status===s} className={`text-xs px-3 py-1.5 rounded-lg font-medium transition disabled:opacity-40 disabled:cursor-not-allowed ${s==="approved"?"bg-green-500/20 text-green-300 hover:bg-green-500/30":s==="declined"?"bg-red-500/20 text-red-300 hover:bg-red-500/30":s==="reviewing"?"bg-blue-500/20 text-blue-300 hover:bg-blue-500/30":"bg-white/10 text-muted hover:bg-white/20"}`}>{s.charAt(0).toUpperCase()+s.slice(1)}</button></form>)}</div></div>)}</div>}
  </div></main></div>);
}
